stages:
  split:
    cmd: python src/data/split_data.py --raw_path data/raw_data/raw.csv 
      --out_dir data/processed_data --test_size 0.2 --random_state 42
    deps:
    - data/raw_data/raw.csv
    - src/data/split_data.py
    outs:
    - data/processed_data/X_test.csv
    - data/processed_data/X_train.csv
    - data/processed_data/y_test.csv
    - data/processed_data/y_train.csv
  scale:
    cmd: python src/data/scale_data.py --in_dir data/processed_data --out_dir 
      data/processed_data
    deps:
    - data/processed_data/X_test.csv
    - data/processed_data/X_train.csv
    - src/data/scale_data.py
    outs:
    - data/processed_data/X_test_scaled.csv
    - data/processed_data/X_train_scaled.csv
